// Run with NODE_PATH pointing to installed Playwright, then: node tests/watchlist.cjs
const {chromium}=require('playwright');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:"chrome"});
 const page=await browser.newPage({viewport:{width:1366,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const root=path.resolve(__dirname,'..');
 await page.route('https://watchlist.test/**',route=>{
  const name=new URL(route.request().url()).pathname.slice(1)||'index.html';
  route.fulfill({body:fs.readFileSync(path.join(root,name)),contentType:(name.endsWith('.js')||name.endsWith('.mjs'))?'text/javascript':name.endsWith('.css')?'text/css':'text/html'});
 });
 await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({body:''}));
 await page.route('https://esm.sh/**',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(__dirname,'mock-supabase.mjs'),'utf8')}));
 await page.goto('https://watchlist.test/');
 await page.locator('#app').waitFor({state:'visible'});
 await page.locator('#accountBtn').click();
 await page.locator('#newPassword').fill('test-password-123');await page.locator('#confirmPassword').fill('different-password');
 await page.locator('#setPasswordForm [type=submit]').click();await page.getByText('Пароли не совпадают.',{exact:true}).waitFor();assert.deepEqual(await page.evaluate(()=>window.authCalls),[]);
 await page.locator('#confirmPassword').fill('test-password-123');await page.locator('#setPasswordForm [type=submit]').click();await page.getByText('Пароль сохранён. Теперь можно входить с паролем или по ссылке.',{exact:true}).waitFor();
 assert.equal(await page.locator('#newPassword').inputValue(),'');
 await page.evaluate(()=>window.rejectPassword=true);await page.locator('#newPassword').fill('test-password-123');await page.locator('#confirmPassword').fill('test-password-123');await page.locator('#setPasswordForm [type=submit]').click();await page.getByText('Пароль не принят',{exact:true}).waitFor();
 assert.equal(await page.locator('#newPassword').isEnabled(),true);
 await page.locator('#accountClose').click();
 async function openFilters(){if(!await page.locator('#filterPanel').evaluate(el=>el.open))await page.locator('#filterPanel>summary').click()}
 async function selectFilter(selector,value){await openFilters();await page.locator(selector).selectOption(value);await page.locator('#applyFilters').click()}
 async function statusFilter(value){await openFilters();await page.locator(`[data-status=${value}]`).click();await page.locator('#applyFilters').click()}
 async function search(q){await page.locator('#searchInput').fill(q);await page.locator('#searchInput').press('Enter');await page.waitForFunction(()=>!document.querySelector('#searchButton').disabled)}
 await search('Мисс Инкогнито');assert.equal(await page.locator('.media-card').count(),1);
 assert.equal(await page.locator('.library-group').count(),1);assert.ok((await page.locator('.library-group summary').textContent()).includes('Дорамы'));
 await page.locator('.library-group summary').click();await page.waitForFunction(()=>!document.querySelector('.library-group').open);assert.equal(await page.locator('.media-card').isVisible(),false);
 await page.locator('#librarySearch').fill('Мисс');assert.equal(await page.locator('.library-group').getAttribute('open'),null);
 await page.locator('.library-group summary').click();await page.locator('#librarySearch').fill('');
 assert.equal(await page.locator('.rating-badge').count(),0);
 await page.locator('.favorite-btn').click();await page.waitForFunction(()=>document.querySelector('.favorite-btn').getAttribute('aria-pressed')==='true');assert.equal(await page.locator('#detailDialog').isVisible(),false);
 await openFilters();await page.locator('#favoriteFilter').check();await page.locator('#applyFilters').click();assert.equal(await page.locator('.media-card').count(),1);
 await page.locator('.favorite-btn').click();await page.locator('.media-card').waitFor({state:'hidden'});
 await openFilters();await page.locator('#resetFilters').click();await page.locator('#applyFilters').click();
 await openFilters();await page.locator('#yearFrom').fill('2026');await page.locator('#applyFilters').click();assert.equal(await page.locator('.media-card').count(),0);
 await openFilters();await page.locator('#yearFrom').fill('2025');await page.locator('#yearTo').fill('2025');await page.locator('#applyFilters').click();assert.equal(await page.locator('.media-card').count(),1);
 await openFilters();await page.locator('#resetFilters').click();await page.locator('#applyFilters').click();
 assert.equal(await page.locator('.duration').textContent(),'≈ 12 ч всего');
 await selectFilter('#durationFilter','600');assert.equal(await page.locator('.media-card').count(),0);
 await selectFilter('#durationFilter','1200');assert.equal(await page.locator('.media-card').count(),1);
 await selectFilter('#durationFilter','unknown');assert.equal(await page.locator('.media-card').count(),0);
 await selectFilter('#durationFilter','all');

 await search('Мисс Инкогнито');assert.equal(await page.locator('#detailDialog').isVisible(),false);await page.getByText('Уже в библиотеке',{exact:true}).waitFor();assert.ok((await page.locator('#existingNotice').textContent()).includes('очередь'));await page.locator('#openExisting').click();await page.locator('#detailDialog').waitFor({state:'visible'});assert.equal(await page.locator('.media-card').count(),1);
 await page.locator('[name=title]').fill('Моё название');await page.locator('[name=status]').selectOption('watched');
 await page.locator('#watchedHint').waitFor({state:'visible'});await page.locator('[name=rating]').selectOption('9');await page.locator('[name=notes]').fill('<script>text</script>');
 await page.locator('#todayBtn').click();await page.locator('#editForm [type=submit]').click();await page.locator('#detailDialog').waitFor({state:'hidden'});
 assert.equal(await page.locator('.rating-badge').textContent(),'★ 9');
 await page.locator('.media-card').click();assert.equal(await page.locator('[name=rating]').inputValue(),'9');assert.equal(await page.locator('[name=notes]').inputValue(),'<script>text</script>');
 await page.locator('[name=status]').selectOption('dropped');await page.locator('#droppedProgress').waitFor({state:'visible'});
 await page.locator('[name=dropped_season]').fill('21');assert.equal(await page.locator('[name=dropped_season]').evaluate(el=>el.checkValidity()),false);await page.locator('[name=dropped_season]').fill('2');await page.locator('[name=dropped_episode]').fill('1500');assert.equal(await page.locator('[name=dropped_episode]').evaluate(el=>el.checkValidity()),false);await page.locator('[name=dropped_episode]').fill('5');
 await page.locator('#editForm [type=submit]').click();await page.locator('#detailDialog').waitFor({state:'hidden'});
 assert.equal(await page.locator('.dropped-progress-note').textContent(),'Место остановки: сезон 2, серия 5');
 await page.locator('.media-card').click();assert.equal(await page.locator('[name=dropped_episode]').inputValue(),'5');
 await page.locator('[name=dropped_episode]').fill('0');assert.equal(await page.locator('[name=dropped_episode]').evaluate(el=>el.checkValidity()),false);await page.locator('[name=dropped_episode]').fill('5');
 await page.locator('[name=status]').selectOption('watched');assert.equal(await page.locator('#droppedProgress').isVisible(),false);
 await page.locator('#editForm [type=submit]').click();await page.locator('#detailDialog').waitFor({state:'hidden'});assert.equal(await page.locator('.dropped-progress-note').count(),0);
 await page.locator('.media-card').click();await page.locator('[name=status]').selectOption('dropped');assert.equal(await page.locator('[name=dropped_season]').inputValue(),'2');assert.equal(await page.locator('[name=dropped_episode]').inputValue(),'5');
 await page.locator('[name=dropped_season]').fill('');await page.locator('[name=dropped_episode]').fill('');await page.locator('#editForm [type=submit]').click();await page.locator('#detailDialog').waitFor({state:'hidden'});assert.equal(await page.locator('.dropped-progress-note').count(),0);
 await page.locator('.media-card').click();await page.locator('[name=status]').selectOption('watched');
 const previousDate=await page.locator('[name=watched_at]').inputValue();
 await page.locator('[name=rewatch_status]').selectOption('planned');
 await page.locator('#editForm [type=submit]').click();await page.locator('#detailDialog').waitFor({state:'hidden'});
 assert.equal(await page.locator('.rewatch-badge').textContent(),'↻ Хочу пересмотреть');
 await page.setViewportSize({width:390,height:844});await page.locator('.media-tile').screenshot({path:'/tmp/watchlist-rating-card.png'});
 const badgeBoxes=await page.evaluate(()=>{const a=document.querySelector('.rating-badge').getBoundingClientRect(),b=document.querySelector('.rewatch-badge').getBoundingClientRect();return {ratingLeft:a.left,rewatchRight:b.right}});assert.ok(badgeBoxes.rewatchRight<badgeBoxes.ratingLeft);
 await page.setViewportSize({width:1366,height:900});
 await statusFilter('watched');await selectFilter('#rewatchFilter','planned');assert.equal(await page.locator('.media-card').count(),1);
 await selectFilter('#rewatchFilter','rewatching');assert.equal(await page.locator('.media-card').count(),0);
 await selectFilter('#rewatchFilter','planned');await page.locator('.media-card').click();
 assert.equal(await page.locator('[name=rewatch_status]').inputValue(),'planned');
 assert.equal(await page.locator('[name=status]').inputValue(),'watched');
 assert.equal(await page.locator('[name=rating]').inputValue(),'9');
 assert.equal(await page.locator('[name=watched_at]').inputValue(),previousDate);
 await page.locator('[name=rewatch_status]').selectOption('rewatching');await page.locator('#editForm [type=submit]').click();await page.locator('#detailDialog').waitFor({state:'hidden'});
 assert.equal(await page.locator('.media-card').count(),0);
 await selectFilter('#rewatchFilter','rewatching');assert.equal(await page.locator('.rewatch-badge').textContent(),'↻ Пересматриваю');
 await page.locator('.media-card').click();assert.equal(await page.locator('[name=watched_at]').inputValue(),previousDate);
 await page.locator('[name=rewatch_status]').selectOption('none');await page.locator('#editForm [type=submit]').click();await page.locator('#detailDialog').waitFor({state:'hidden'});
 await selectFilter('#rewatchFilter','none');assert.equal(await page.locator('.media-card').count(),1);assert.equal(await page.locator('.rewatch-badge').count(),0);
 await selectFilter('#rewatchFilter','all');await statusFilter('all');await page.locator('.media-card').click();
 assert.equal(await page.locator('[name=rating]').inputValue(),'9');
 await page.evaluate(()=>window.failSave=true);await page.locator('#editForm [type=submit]').click();await page.getByText('Не удалось сохранить: Сбой сохранения').waitFor();assert.equal(await page.locator('[name=title]').isEnabled(),true);
 await page.evaluate(()=>window.failSave=false);
 await page.evaluate(()=>document.querySelector('#detailDialog').scrollTop=0);
 await page.screenshot({path:'/tmp/watchlist-desktop.png'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/watchlist-mobile.png'});
 assert.ok(await page.evaluate(()=>document.querySelector('#detailDialog').scrollWidth<=document.querySelector('#detailDialog').clientWidth));
 await page.locator('#deleteBtn').click();await page.locator('#confirmDialog [value=cancel]').click();assert.equal(await page.locator('.media-card').count(),1);
 await page.locator('#deleteBtn').click();await page.locator('#confirmDialog [value=delete]').click();await page.locator('#detailDialog').waitFor({state:'hidden'});assert.equal(await page.locator('.media-card').count(),0);
 await search('Дюна');assert.equal(await page.locator('.result-card').count(),2);assert.equal(await page.locator('.media-card').count(),0);
 await page.locator('.result-card').first().click();await page.locator('.media-card').waitFor();
 await search('нет');assert.equal(await page.locator('#searchHint').isVisible(),true);assert.equal(await page.locator('.result-card').count(),0);
 await search('ошибка');await page.getByText('Ошибка сети',{exact:true}).waitFor();
 const calls=await page.evaluate(()=>window.calls);
 for(const c of calls){if(c.kind==='insert')assert.equal(c.payload.user_id,'user-1');else assert.equal(c.filters.user_id,'user-1')}
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#logoutBtn').click();await page.locator('#authScreen').waitFor({state:'visible'});assert.equal(await page.locator('.media-card').count(),0);
 assert.equal(await page.locator('.password-login').getAttribute('open'),null);
 await page.locator('#emailInput').fill('test@example.com');await page.locator('#loginForm [type=submit]').click();await page.getByText('Ссылка для входа отправлена на почту ✦',{exact:true}).waitFor();
 await page.locator('.password-login summary').click();await page.locator('#passwordEmail').fill('test@example.com');await page.locator('#loginPassword').fill('wrong-password');await page.locator('#passwordLoginForm [type=submit]').click();await page.getByText('Не подошли email или пароль. Можно войти по ссылке.',{exact:true}).waitFor();
 assert.equal(await page.locator('#loginPassword').inputValue(),'');
 await page.locator('#forgotPassword').click();assert.equal(await page.locator('#emailInput').inputValue(),'test@example.com');
 await page.locator('.password-login summary').click();await page.locator('#loginPassword').fill('test-password-123');await page.locator('#passwordLoginForm [type=submit]').click();await page.locator('#app').waitFor({state:'visible'});
 assert.equal(await page.locator('#loginPassword').inputValue(),'');await page.locator('.media-card').waitFor();assert.equal(await page.locator('.media-card').count(),1);
 await page.locator('#accountBtn').click();await page.screenshot({path:'/tmp/watchlist-account-mobile.png'});
 assert.ok(await page.evaluate(()=>document.querySelector('#accountDialog').scrollWidth<=document.querySelector('#accountDialog').clientWidth));
 await page.locator('#accountClose').click();
 await search('Мисс Инкогнито');assert.equal(await page.locator('.library-group').count(),2);
 await selectFilter('#typeFilter','movie');assert.equal(await page.locator('.library-group').count(),1);assert.ok((await page.locator('.library-group summary').textContent()).includes('Фильмы'));
 await selectFilter('#typeFilter','all');
 await search('Мисс Инкогнито');assert.equal(await page.locator('#detailDialog').isVisible(),false);
 await page.locator('#existingNotice').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/watchlist-groups-mobile.png',fullPage:true});
 await page.setViewportSize({width:1366,height:900});await page.screenshot({path:'/tmp/watchlist-groups-desktop.png',fullPage:true});
 assert.equal(await page.locator('#filterPanel').evaluate(el=>el.open),false);
 await openFilters();await page.locator('#genreFilters input[value="драма"]').check();await page.locator('#applyFilters').click();assert.equal(await page.locator('#filterCount').textContent(),'1');assert.equal(await page.locator('.media-card').count(),2);
 await openFilters();await page.locator('#resetFilters').click();await page.locator('#applyFilters').click();assert.equal(await page.locator('#filterCount').isVisible(),false);
 await page.locator('#sortPanel>summary').click();await page.locator('[name=librarySort][value="title-asc"]').check();assert.equal(await page.locator('#sortPanel').evaluate(el=>el.open),false);
 assert.ok((await page.locator('#librarySelection').textContent()).includes('А → Я'));
 await page.locator('#sortPanel>summary').click();await page.keyboard.press('Escape');assert.equal(await page.locator('#sortPanel').evaluate(el=>el.open),false);
 await page.setViewportSize({width:390,height:844});await openFilters();await page.screenshot({path:'/tmp/watchlist-filters-mobile.png'});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#applyFilters').click();await page.setViewportSize({width:1366,height:900});await page.locator('#sortPanel>summary').click();await page.screenshot({path:'/tmp/watchlist-sort-desktop.png'});
 await page.keyboard.press('Escape');await page.locator('#groupToggle').click();assert.equal(await page.locator('.library-group').count(),0);assert.equal(await page.locator('.flat-grid .media-card').count(),2);
 assert.deepEqual(await page.locator('.primary-genre').allTextContents(),['драма','драма']);
 await page.locator('#sortPanel>summary').click();await page.locator('[name=librarySort][value="title-desc"]').check();assert.deepEqual(await page.locator('.flat-grid h4').allTextContents(),['Мисс Инкогнито','Дюна']);
 await selectFilter('#typeFilter','movie');assert.equal(await page.locator('.flat-grid .media-card').count(),1);
 await selectFilter('#typeFilter','all');await page.locator('#groupToggle').click();assert.equal(await page.locator('.library-group').count(),2);
 await page.locator('#accountBtn').click();await page.locator('#usernameInput').fill('taken');await page.locator('#usernameForm button').click();await page.getByText('Это имя уже занято. Попробуй другое.',{exact:true}).waitFor();
 await page.locator('#usernameInput').fill('Zulf');await page.locator('#usernameForm button').click();await page.waitForFunction(()=>document.querySelector('#userEmail').textContent==='zulf');await page.locator('#accountClose').click();
 await page.locator('#settingsBtn').click();await page.locator('#sectionOrder [data-index="3"][data-move="-1"]').click();await page.locator('#sectionOrder [data-index="2"][data-move="-1"]').click();await page.locator('#sectionOrder [data-index="1"][data-move="-1"]').click();await page.locator('#saveOrder').click();await page.locator('#settingsNote').filter({hasText:'Сохранено'}).waitFor();await page.locator('#settingsClose').click();
 assert.equal(await page.locator('.library-group').first().getAttribute('data-group'),'drama');
 await page.locator('#logoutBtn').click();await page.locator('.password-login summary').click();await page.locator('#passwordEmail').fill('zulf');await page.locator('#loginPassword').fill('wrong');await page.locator('#passwordLoginForm [type=submit]').click();await page.getByText('Не подошли имя пользователя или пароль. Можно войти по ссылке.',{exact:true}).waitFor();
 await page.locator('#loginPassword').fill('test-password-123');await page.locator('#passwordLoginForm [type=submit]').click();await page.waitForFunction(()=>document.querySelector('#userEmail').textContent==='zulf');await page.locator('.library-group').first().waitFor();assert.equal(await page.locator('.library-group').first().getAttribute('data-group'),'drama');
 await page.setViewportSize({width:390,height:844});await page.locator('#settingsBtn').click();await page.screenshot({path:'/tmp/watchlist-settings-mobile.png'});await page.locator('#settingsClose').click();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('.media-card[data-id="row-1"]').click();await page.locator('[name=status]').selectOption('dropped');assert.equal(await page.locator('#droppedProgress').count(),0);await page.locator('#dialogClose').click();
 assert.equal(await page.locator('.hero h2').textContent(),'Моя медиатека');assert.equal(await page.locator('.hero-copy').count(),0);
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'/tmp/watchlist-compact-header.png'});
 await page.locator('#settingsBtn').click();await page.locator('#newTypeName').fill('Концерты <live>');await page.locator('#newTypeForm button').click();await page.locator('#typeManager .manager-row').filter({hasText:'Концерты <live>'}).waitFor();
 await page.locator('#newListName').fill('На вечер');await page.locator('#newListForm button').click();await page.locator('#listManager .manager-row').filter({hasText:'На вечер'}).waitFor();await page.locator('#settingsClose').click();
 await page.locator('.media-card[data-id="row-1"]').click();await page.locator('#editForm [name=category]').selectOption({label:'Концерты <live>'});await page.locator('#editForm [name=list_ids]').check();await page.locator('#editForm [name=tags]').fill('Уютное, с друзьями, уютное');await page.locator('#editForm [type=submit]').click();await page.locator('#detailDialog').waitFor({state:'hidden'});
 assert.ok((await page.locator('.library-group summary').allTextContents()).some(t=>t.includes('Концерты <live>')));
 await openFilters();await page.locator('#listFilter').selectOption({label:'На вечер'});await page.locator('#tagFilters input[value="уютное"]').check();await page.locator('#applyFilters').click();assert.equal(await page.locator('.media-card').count(),1);
 await openFilters();await page.locator('#resetFilters').click();await page.locator('#applyFilters').click();
 await page.locator('.media-card[data-id="row-1"]').click();const cardDate=await page.locator('#editForm [name=watched_at]').inputValue();await page.locator('#openTitleDiary').click();await page.waitForFunction(()=>!document.querySelector('#diarySave').disabled);
 await page.locator('#diaryDate').fill('2026-01-10');await page.locator('#diaryRating').selectOption('8');await page.locator('#diaryNotes').fill('Первый просмотр');await page.locator('#diarySave').click();await page.locator('.diary-entry').filter({hasText:'Первый просмотр'}).waitFor();
 await page.locator('#diaryDate').fill('2026-02-10');await page.locator('#diaryRating').selectOption('10');await page.locator('#diaryRewatch').check();await page.locator('#diaryNotes').fill('Пересмотр с друзьями');await page.locator('#diarySave').click();await page.locator('.diary-entry').filter({hasText:'Пересмотр с друзьями'}).waitFor();assert.equal(await page.locator('.diary-entry').count(),2);
 await page.locator('.diary-entry').first().locator('[data-edit-entry]').click();await page.locator('#diaryNotes').fill('Новая заметка');await page.locator('#diarySave').click();await page.locator('.diary-entry').filter({hasText:'Новая заметка'}).waitFor();assert.equal(await page.locator('.diary-entry').count(),2);
 await page.locator('.diary-entry').last().locator('[data-delete-entry]').click();await page.locator('#actionConfirm [value=confirm]').click();await page.waitForFunction(()=>document.querySelectorAll('.diary-entry').length===1);
 await page.evaluate(()=>window.failDiary=true);await page.locator('#diaryNotes').fill('Не терять заметку');await page.locator('#diarySave').click();await page.locator('#diaryNote').filter({hasText:'Ошибка дневника'}).waitFor();assert.equal(await page.locator('#diaryNotes').inputValue(),'Не терять заметку');await page.evaluate(()=>window.failDiary=false);
 await page.locator('#diaryClose').click();assert.equal(await page.locator('#editForm [name=watched_at]').inputValue(),cardDate);await page.locator('#dialogClose').click();
 await page.locator('#statisticsBtn').click();await page.locator('.diary-totals').waitFor();assert.deepEqual(await page.locator('.diary-totals strong').allTextContents(),['1','1','1']);assert.ok((await page.locator('#diaryStatistics').textContent()).includes('драма'));await page.screenshot({path:'/tmp/watchlist-diary-statistics.png'});await page.locator('#statisticsClose').click();
 await page.locator('#settingsBtn').click();await page.locator('#typeManager .manager-row').filter({hasText:'Концерты <live>'}).locator('button').click();await page.locator('#actionConfirm [value=confirm]').click();await page.locator('#typeManager .manager-row').filter({hasText:'Концерты <live>'}).waitFor({state:'hidden'});
 await page.locator('#listManager .manager-row').filter({hasText:'На вечер'}).locator('button').click();await page.locator('#actionConfirm [value=confirm]').click();await page.locator('#listManager .manager-row').filter({hasText:'На вечер'}).waitFor({state:'hidden'});await page.locator('#settingsClose').click();assert.equal(await page.locator('.media-card').count(),2);assert.ok((await page.locator('.library-group summary').allTextContents()).some(t=>t.includes('Без типа')));
 await page.locator('#accountBtn').click();await page.locator('#genderInput').selectOption('male');await page.locator('#genderForm button').click();await page.locator('#genderNote').filter({hasText:'Сохранено'}).waitFor();await page.locator('#accountClose').click();assert.ok((await page.locator('#stats').textContent()).includes('посмотрел'));
 await page.locator('.media-card[data-id="row-1"]').click();assert.equal(await page.locator('[name=is_favorite]').count(),0);await page.locator('[name=status]').selectOption('paused');assert.equal(await page.locator('#rewatchField').isVisible(),false);await page.locator('[name=paused_timestamp]').fill('02:00:00');await page.locator('#editForm [type=submit]').click();await page.locator('#editMessage').filter({hasText:'не может быть позже'}).waitFor();await page.locator('[name=paused_timestamp]').fill('00:25:30');await page.locator('#editForm [type=submit]').click();await page.locator('#detailDialog').waitFor({state:'hidden'});
 await page.locator('#stats [data-quick-status=paused]').click();assert.equal(await page.locator('.media-card').count(),1);assert.equal(await page.locator('#statusFilters [data-status=paused]').getAttribute('class'),'segment active');await page.locator('.media-card').click();assert.equal(await page.locator('[name=paused_timestamp]').inputValue(),'00:25:30');await page.locator('#dialogClose').click();await page.locator('#stats [data-quick-status=all]').click();assert.equal(await page.locator('.media-card').count(),2);
 await page.locator('.media-card').filter({hasText:'Мисс Инкогнито'}).click();await page.locator('[name=status]').selectOption('paused');await page.locator('[name=dropped_season]').fill('2');await page.locator('[name=dropped_episode]').fill('4');await page.locator('#editForm [type=submit]').click();await page.locator('#detailDialog').waitFor({state:'hidden'});await page.locator('.media-card').filter({hasText:'Мисс Инкогнито'}).click();assert.equal(await page.locator('[name=dropped_episode]').inputValue(),'4');await page.locator('#dialogClose').click();
 await page.evaluate(()=>window.seedHistory([{id:'auto-1',user_id:'user-1',item_id:'row-1',event_kind:'completed',source:'automatic',watched_on:null,rating:8},{id:'auto-2',user_id:'user-1',item_id:'row-3',event_kind:'status',source:'automatic',watched_on:'2026-09-27',status_value:'paused'}]));
 await page.locator('#diaryBtn').click();await page.waitForFunction(()=>document.querySelectorAll('.diary-entry').length===2);assert.ok((await page.locator('#diaryEntries').textContent()).includes('Пауза'));await page.locator('#diaryClose').click();
 await page.locator('.media-card[data-id="row-1"]').click();await page.locator('#openTitleDiary').click();await page.waitForFunction(()=>document.querySelectorAll('.diary-entry').length===1);assert.equal(await page.locator('#diaryItem option').count(),1);await page.locator('#diaryClose').click();await page.locator('#dialogClose').click();
 await page.locator('#statisticsBtn').click();await page.locator('.diary-totals').waitFor();assert.deepEqual(await page.locator('.diary-totals strong').allTextContents(),['1','0','1']);assert.ok((await page.locator('#diaryStatistics').textContent()).includes('Без известной даты: 1'));await page.locator('#statisticsClose').click();
 await page.locator('#settingsBtn').click();await page.locator('[data-theme-choice=pink]').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'pink');assert.equal(await page.locator('[data-theme-choice=pink]').getAttribute('aria-pressed'),'true');await page.locator('#settingsClose').click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'/tmp/watchlist-pink-mobile.png'});await page.reload();await page.locator('#app').waitFor({state:'visible'});assert.equal(await page.locator('html').getAttribute('data-theme'),'pink');await page.locator('#settingsBtn').click();await page.locator('[data-theme-choice=lime]').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'lime');await page.locator('#settingsClose').click();
 assert.deepEqual(errors,[]);
 console.log('PASS: pause for movies/series, timestamps, gender labels, quick status filters, custom types with HTML characters, lists/tags/filtering, diary CRUD/errors, repeat statistics, optional password setup/login/errors/magic fallback, local duration/filter, rewatch flags/filter/clear preserve status/rating/date, quick add, duplicate, ambiguity, edit, optional fields, errors, delete cancel/confirm, user scoping, logout, desktop/mobile layout, no JS errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
